# my repo
apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  annotations:
    policies.kyverno.io/title: Block Access to EC2 Metadata
    policies.kyverno.io/category: ECS Best Practices
    policies.kyverno.io/severity: medium
    policies.nirmata.io/remediation-docs: N/A
    policies.nirmata.io/remediation: N/A
    policies.kyverno.io/description: |
      When you run your tasks on Amazon EC2 instances, it is recommended that you block access to Amazon EC2 metadata to prevent your containers from inheriting the role assigned to those instances. If your applications have to call an AWS API action, use IAM roles for tasks instead.
  labels:
    ecs.aws.tags.kyverno.io: block-access-ec2-metadata
  name: block-access-ec2-metadata
spec:
  rules:
  - name: block-access-ec2-metadata-rule
    match:
      any:
      # - type: aws_ecs_service
      - type: aws_ecs_task_definition
    assert:
      all:
      - message: When running tasks on EC2 instances, block access to EC2 metadata to prevent containers from inheriting instance roles. Use IAM roles for tasks instead.
        check:
          values:
              # {jmespathexpresssion}